### ISSUE TITLE
Pair.py check for firmware before flashing

### ISSUE THREAD

**Issue by RaghavRao** [uunicorn/python-validity#11]
If the firmware file isn't where it's supposed to be, pair.py starts the initial flash and fails when searching for the firmware file.
Running it again warns that the flash is already partitioned.

Maybe pair.py could check if the fw is present in the firmware home first thing upon opening?

Edit: It seems the proper way is to use validity-sensor-initializer. Perhaps just updating the steps in the readme to reflect this is enough?

**Comment by uunicorn** [comment]
Correct, `validity-sensor-initializer` is a proper way to initialize the sensor at the moment. `setup.py` installs it in `/usr/bin`, while `pair.py` and friends are going to `/usr/share/python-validity/playground/`. It is still possible to use them for debugging purposes.

**Comment by RaghavRao** [comment]
Makes sense. Thanks
