### ISSUE TITLE
verify-no-match after successful enroll [Fedora 40; thinkpad t480s]

### ISSUE THREAD

**Issue by coddest** [uunicorn/python-validity#195]
I cannot verify successfully, even after enrolling without issues.

```
[...]
Enroll result: enroll-stage-passed
Enroll result: enroll-completed
coddest@fedora:~$ fprintd-verify
Using device /net/reactivated/Fprint/Device/4
Listing enrolled fingers:
 - #0: right-index-finger
Verify started!
Verifying: any
Verify result: verify-no-match (done)
```

**Comment by mikpotik** [comment]
Maybe this will help:

https://github.com/uunicorn/python-validity/issues/189#issuecomment-2294960949

**Comment by coddest** [comment]
> Maybe this will help:
> 
> [#189 (comment)](https://github.com/uunicorn/python-validity/issues/189#issuecomment-2294960949)

I had a windows 10 previously installed, but the fedora I have now setup was clean install, no dual boot.
Do you think it still might be related, would I have to install windows to do the steps you mentioned?

**Comment by mikpotik** [comment]
> > Maybe this will help:
> > [#189 (comment)](https://github.com/uunicorn/python-validity/issues/189#issuecomment-2294960949)
> 
> I had a windows 10 previously installed, but the fedora I have now setup was clean install, no dual boot. Do you think it still might be related, would I have to install windows to do the steps you mentioned?

No matter what OS you have or have had installed, I think the registered finger data is stored in the fingerprint recognition module itself. So they will be stored there permanently, regardless of the OS installed. If you used fingerprint recognition on Windows 10, they are in the module. You need to reset them.

**Comment by mikpotik** [comment]
Or you can try this, I found it after I solved the problem through WINDOWS 10:

https://github.com/uunicorn/python-validity/issues/167#issuecomment-1931445835
after killed the process that uses your fingerprint sensor. Do a reset according to the author's instructions:

```
$ sudo systemctl stop python3-validity
$ sudo validity-sensors-firmware
$ sudo python3 /usr/share/python-validity/playground/factory-reset.py

# At some of the above points you may get a 'device busy' error,
# depending on how systemctl plays along. Kill offending processes if
# necessary, or re-run the systemctl stop python3-validity command, 
# in case it has automatically been restarted, or or kill other
# offending processes.

$ sudo systemctl start python3-validity
$ fprintd-enroll
```

Here's how I killed the process on my PC:

```
mikpotik@Lenovo-P51:~$ lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 138a:0097 Validity Sensors, Inc.
Bus 001 Device 003: ID 04f2:b5ab Chicony Electronics Co., Ltd Integrated Camera
Bus 001 Device 002: ID 046d:c52f Logitech, Inc. Unifying Receiver
Bus 001 Device 006: ID 8087:0a2b Intel Corp. Bluetooth wireless interface
Bus 001 Device 005: ID 0765:5010 X-Rite, Inc. X-Rite Pantone Color Sensor
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
mikpotik@Lenovo-P51:~$ sudo lsof /dev/bus/usb/001/004
lsof: WARNING: can't stat() fuse.portal file system /run/user/1000/doc
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse.viber.AppImage file system /tmp/.mount_viber.vV6ftM
      Output information may be incomplete.
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
python3 1351 root    9u   CHR  189,3      0t0  425 /dev/bus/usb/001/004
mikpotik@Lenovo-P51:~$ kill -9 1351
bash: kill: (1351) - Дію заборонено
mikpotik@Lenovo-P51:~$ sudo kill -9 1351
mikpotik@Lenovo-P51:~$ sudo lsof /dev/bus/usb/001/004
lsof: WARNING: can't stat() fuse.portal file system /run/user/1000/doc
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse.viber.AppImage file system /tmp/.mount_viber.vV6ftM
      Output information may be incomplete.
mikpotik@Lenovo-P51:~$
```

**Comment by coddest** [comment]
I already tried the factory-reset, it did not fix anything.
But I thought I will try again and see how it goes, it still didn't work, but I kept digging around, and broke everything even more, I had to reinstall a lot of things, and this time it worked.

So I have no idea what finally fixed the issue.
