### ISSUE TITLE
Fingerprint recognition unreliable on 009a

### ISSUE THREAD

**Issue by mlalkaka** [uunicorn/python-validity#46]
First off, thank you so much for working on this!

I have a ThinkPad T480s with the Validity 009a fingerprint reader. I enrolled and registered my fingerprint fine, but I've noticed that recognizing the fingerprint doesn't seem to be working very well. It only recognizes the fingerprint very rarely. I tried re-registering the fingerprint and tried multiple different finger positions, but I got the same result.

Is this a known issue? Any tips on how I can improve this? Let me know if I can provide more info to diagnose the issue.

**Comment by himekifee** [comment]
You can try do a factory reset to achieve a calibration, not sure if that works for you..

**Comment by mlalkaka** [comment]
How do I do a factory reset?

**Comment by mlalkaka** [comment]
Oh, found what you were referring to: https://github.com/uunicorn/python-validity#error-situations. I'll give that a try

**Comment by uunicorn** [comment]
> Is this a known issue? Any tips on how I can improve this?

I had similar issues when I was accidentally holding my palm against the sensor while it was calibrating.
I was able to recover from this state by deleting the `/usr/share/python-validity/calib-data.bin` file and performing a factory reset.

**Comment by elmir-becirovic** [comment]
I am facing the same issue as mentioned here. I have noticed that if I tap my finger really fast on the scanner it manages to match it, but if I am a bit slower it will fail to match. Any ideas?

**Comment by mlalkaka** [comment]
Thanks @himekifee and @uunicorn . Factory resetting as described in [Error Situations](https://github.com/uunicorn/python-validity#error-situations) worked! The fingerprint sensor has been reliable and pretty fast now. Closing this issue.
