### ISSUE TITLE
Enroll-failed on Thinkpad T480 with 06cb:009a Synaptics

### ISSUE THREAD

**Issue by kendoori** [uunicorn/python-validity#57]
I have a Thinkpad T480 which has a 06cb:009a Synaptics, Inc. fingerprint reader. 

When I go through the enrollment process, this is what I see.

![CLI output](https://i.imgur.com/nmzU94W.png)

I am running Linux Mint 20 with Cinnamon.

**Comment by uunicorn** [comment]
Could it be that you have already enrolled your `right-index-finger`? 
You can check what's enrolled with `fprintd-list kenny`.

**Comment by kendoori** [comment]
@uunicorn Thanks! Oops. Did a fprintd-delete to my user and was able to enroll. Cosing

**Comment by johanricher** [comment]
I had the same problem and `fprintd-delete _my_username_` then `fprintd-enroll` again worked for me. Thanks!
