### ISSUE TITLE
Can't install with yay from Arch AUR

### ISSUE THREAD

**Issue by apl1341** [uunicorn/python-validity#69]
I've been trying to install this driver on my ThinkPad T480s but I keep running into the same error where yay cant find the dependencies for it. I also tried installing the deps from git directly with no luck.

Going to the AUR webpage and looking for fprintd-clients and open-fprintd just gives a 404.

See below:

`
   ~ ❯ yay -S python-validity-git                                                                                                                              3s   09:18:09 PM
 -> Could not find all required packages:
        fprintd-clients (Wanted by: python-validity-git)
        open-fprintd (Wanted by: python-validity-git)
`

**Comment by KindlyPizza** [comment]
Same, just reloaded Arch on my machine and suddenly found that dependencies were missing.

**Comment by jugendhacker** [comment]
Yeah I also searched aur-request mailing list for anything about what's going on but the package just disappeared.... I'll maybe ask on aur-general

**Comment by jugendhacker** [comment]
Okay so I asked on aur-general and they told me the packages where removed because the maintainer deleted their account. But luckily the git for the package is still there and so I republished them.

**Comment by KindlyPizza** [comment]
many thanks upon you.

**Comment by apl1341** [comment]
Thanks so much! Just got it working on my machine.
