### ISSUE TITLE
06cb:009a verify-no-match after enroll-completed

### ISSUE THREAD

**Issue by HankvanHinton** [uunicorn/python-validity#79]
Hello everyone, 

on my Thinkpad T480s running Manjaro KDE (Kernel 5.9.16), I can enroll my finger but verification then always fails. I've tried resetting and re-enrolling my finger multiple times. 
```

Using device /net/reactivated/Fprint/Device/0
Enrolling right-index-finger finger.
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-stage-passed
Enroll result: enroll-completed

Using device /net/reactivated/Fprint/Device/0
Listing enrolled fingers:
 - #0: WINBIO_ANSI_381_POS_RH_INDEX_FINGER
Verify result: verify-no-match (done)
```

Please let me know if I need to supply more information.

**Comment by KoalaV2** [comment]
+1 Same issue here. T480s and arch linux.

**Comment by KoalaV2** [comment]
Any updates on this?

**Comment by blondiejon** [comment]
+1 Also for me. T480s and Elementary OS 6 Odin.

**Comment by biladina** [comment]
+1 its same here, using P52 with Fedora 34..

**Comment by heeen** [comment]
I had the same issue on a T480, I did the reset procedure and rebooted that seemed to fix it

**Comment by uunicorn** [comment]
A factory reset forces a calibration. If you put your finger/palm on the sensor during the calibration, all subsequent attempts to enroll/verify will be very unreliable. `06cb:009a` device is special in a sense that calibration results are partly stored on both the device and the host. Whenever you calibrate the sensor, remember to delete `/usr/share/python-validity/calib-data.bin`.

**Comment by KoalaV2** [comment]
Can confirm factory reset fixed it for me, thanks!

**Comment by biladina** [comment]
beside factory reset, try to clear fingerprint data from BIOS also fix my problem..
