### ISSUE TITLE
No PPA for Ubuntu 21.04

### ISSUE THREAD

**Issue by 12people** [uunicorn/python-validity#83]
On adding the PPA via the steps described in the README, I get the message:

> The repository 'http://ppa.launchpad.net/uunicorn/open-fprintd/ubuntu hirsute Release' does not have a Release file.

(And trying to install afterward, the packages can't be found.)

**Comment by synaps13** [comment]
Apparently there is PPA distribution for `hirsute` aka ubuntu 21. What worked for me was modifying it to `focal` aka ubuntu 20 PPA.
![image](https://user-images.githubusercontent.com/48735170/127639559-c4b5a3ea-9252-4d88-88dd-c8cf6bf9775d.png)

**Comment by uunicorn** [comment]
PPA for 21.04 added.
